/**
 * Curated parcel sources. Every entry was opened and point-queried before it
 * went in: geometry, fields, CORS and whether owner names actually come back.
 * Statewide layers first, then counties that publish names where their state
 * layer does not. Anything not listed here is found at runtime by
 * parcelDiscovery.ts.
 */
import type { ParcelSource } from './parcels'

export const STATEWIDE_SOURCES: ParcelSource[] = [
  {
    id: 'oh-statewide',
    label: 'Ohio Statewide Parcels (OGRIP)',
    shortLabel: 'Ohio statewide',
    url: 'https://services2.arcgis.com/MlJ0G8iWUyC7jAmu/arcgis/rest/services/OhioStatewidePacels_full_view/FeatureServer/0',
    fields: { parcelId: 'LocalParcelID', mailAddress: 'MailAddressAll', situs: 'SitusAddressAll', acres: 'LandArea', landUse: 'StateLUC', county: 'County', link: 'CAMADataSite' },
    county: null,
    state: 'OH',
    extent: [-84.82, 38.4, -80.52, 41.98],
    kind: 'statewide',
    recordsUrl: 'https://ohioparcels-geohio.hub.arcgis.com/',
  },

  // ---------- East (verified 2026-10-09) ----------
  {
    id: 'ct-statewide',
    label: 'Connecticut CAMA and Parcel Layer (CT OPM)',
    shortLabel: 'Connecticut statewide',
    url: 'https://services3.arcgis.com/3FL1kr7L4LvwA2Kb/arcgis/rest/services/Connecticut_CAMA_and_Parcel_Layer/FeatureServer/0',
    fields: { parcelId: 'Parcel_ID', owner: 'Owner', owner2: 'Co_Owner', mailParts: ['Mailing_Address', 'Mailing_City', 'Mailing_State', 'Mailing_Zip'], situs: 'Location', acres: 'Land_Acres', landUse: 'State_Use_Description' },
    county: null,
    state: 'CT',
    extent: [-73.7422, 40.9799, -71.7813, 42.0526],
    kind: 'statewide',
    recordsUrl: 'https://geodata.ct.gov/datasets/ctgis::connecticut-cama-and-parcel-layer',
  },
  {
    id: 'de-statewide',
    label: 'Delaware State Parcels (FirstMap)',
    shortLabel: 'Delaware statewide',
    url: 'https://enterprise.firstmap.delaware.gov/arcgis/rest/services/PlanningCadastre/DE_StateParcels/FeatureServer/0',
    fields: { parcelId: 'PIN', acres: 'ACRES', county: 'COUNTY' },
    county: null,
    state: 'DE',
    extent: [-75.789, 38.4508, -75.0494, 39.8395],
    kind: 'statewide',
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=35154346e73748ef915d863651839ccc',
  },
  {
    id: 'fl-statewide',
    label: 'Florida Statewide Parcels (FL DOR, Florida GIO)',
    shortLabel: 'Florida statewide',
    url: 'https://services9.arcgis.com/Gh9awoU677aKree0/arcgis/rest/services/Florida_Statewide_Cadastral/FeatureServer/0',
    fields: { parcelId: 'PARCEL_ID', owner: 'OWN_NAME', mailName: 'FIDU_NAME', mailParts: ['OWN_ADDR1', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIPCD'], situs: 'PHY_ADDR1', landUse: 'DOR_UC' },
    county: null,
    state: 'FL',
    extent: [-87.638, 24.4117, -79.7702, 31.0426],
    kind: 'statewide',
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=efa909d6b1c841d298b0a649e7f71cf2',
  },
  {
    id: 'ma-statewide',
    label: 'Massachusetts Property Tax Parcels (MassGIS)',
    shortLabel: 'Massachusetts statewide',
    url: 'https://services1.arcgis.com/hGdibHYSPO59RG1h/arcgis/rest/services/Massachusetts_Property_Tax_Parcels/FeatureServer/0',
    fields: { parcelId: 'LOC_ID', owner: 'OWNER1', mailParts: ['OWN_ADDR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP'], situs: 'SITE_ADDR', acres: 'LOT_SIZE', landUse: 'USE_DESC' },
    county: null,
    state: 'MA',
    extent: [-73.5333, 41.2305, -69.8993, 42.8883],
    kind: 'statewide',
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=73d4c766167848b795f1048cad3919c7',
  },
  {
    id: 'md-statewide',
    label: 'Maryland Parcel Boundaries (MDP and SDAT)',
    shortLabel: 'Maryland statewide',
    url: 'https://mdgeodata.md.gov/imap/rest/services/PlanningCadastre/MD_ParcelBoundaries/MapServer/0',
    fields: { parcelId: 'ACCTID', mailParts: ['OWNADD1', 'OWNCITY', 'OWNSTATE', 'OWNERZIP'], situs: 'ADDRESS', acres: 'ACRES', landUse: 'DESCLU', link: 'SDATWEBADR' },
    county: null,
    state: 'MD',
    extent: [-79.4877, 37.912, -75.0496, 39.7284],
    kind: 'statewide',
    pageSize: 1000,
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=21c0e151ad754cd096ecac5fd1b01e40',
  },
  {
    id: 'me-statewide',
    label: 'Maine Parcels, Organized Towns (MEGIS)',
    shortLabel: 'Maine statewide',
    url: 'https://services1.arcgis.com/RbMX0mRVOFNTdLzd/arcgis/rest/services/Maine_Parcels_Organized_Towns/FeatureServer/10',
    ownerTable: { url: 'https://services1.arcgis.com/RbMX0mRVOFNTdLzd/arcgis/rest/services/Maine_Parcels_Organized_Towns/FeatureServer/9', joinField: 'STATE_ID' },
    fields: { parcelId: 'STATE_ID', owner: 'OWNER1', owner2: 'OWNER2', mailParts: ['OWN_ADDR1', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP'], situs: 'PROP_LOC', acres: 'LOT_SIZE', landUse: 'LAND_USE_D', county: 'COUNTY' },
    county: null,
    state: 'ME',
    extent: [-71.1309, 42.971, -66.8493, 47.3615],
    kind: 'statewide',
    ownerPartial: true,
    recordsUrl: 'https://maine.maps.arcgis.com/apps/webappviewer/index.html?id=28e35c8fcf514d2685357b78bdd0b246',
  },
  {
    id: 'nc-statewide',
    label: 'North Carolina Parcels (NC OneMap)',
    shortLabel: 'North Carolina statewide',
    url: 'https://services.nconemap.gov/secure/rest/services/NC1Map_Parcels/FeatureServer/1',
    fields: { parcelId: 'parno', owner: 'ownname', owner2: 'ownname2', mailParts: ['mailadd', 'mcity', 'mstate', 'mzip'], situs: 'siteadd', acres: 'gisacres', landUse: 'parusedesc', county: 'cntyname' },
    county: null,
    state: 'NC',
    extent: [-84.32, 33.84, -75.46, 36.59],
    kind: 'statewide',
    recordsUrl: 'https://www.nconemap.gov/pages/parcels',
  },
  {
    id: 'nh-statewide',
    label: 'NH Parcel Mosaic (NH GRANIT)',
    shortLabel: 'New Hampshire statewide',
    url: 'https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1',
    fields: { parcelId: 'nh_gis_id', situs: 'streetaddress', landUse: 'slu' },
    county: null,
    state: 'NH',
    extent: [-72.56, 42.66, -70.61, 45.31],
    kind: 'statewide',
    recordsUrl: 'https://experience.arcgis.com/experience/148ee63e49394146b8d3f2aeaa2400c4',
  },
  {
    id: 'nj-statewide',
    label: 'Parcels and MOD-IV Composite of NJ (NJOGIS)',
    shortLabel: 'New Jersey statewide',
    url: 'https://services2.arcgis.com/XVOqAjTOJ5P6ngMu/arcgis/rest/services/Parcels_Composite_NJ_WM/FeatureServer/0',
    fields: { parcelId: 'PAMS_PIN', mailParts: ['ST_ADDRESS', 'CITY_STATE', 'ZIP_CODE'], situs: 'PROP_LOC', acres: 'CALC_ACRE', landUse: 'PROP_CLASS', county: 'COUNTY' },
    county: null,
    state: 'NJ',
    extent: [-75.5596, 38.9247, -73.9025, 41.3569],
    kind: 'statewide',
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=533599bbfbaa4748bf39faf1375a8a9c',
  },
  {
    id: 'ny-statewide',
    label: 'NYS Tax Parcels Public (NYS ITS)',
    shortLabel: 'New York statewide',
    url: 'https://services6.arcgis.com/EbVsqZ18sv1kVJ3k/arcgis/rest/services/NYS_Tax_Parcels_Public/FeatureServer/1',
    fields: { parcelId: 'SWIS_SBL_ID', owner: 'PRIMARY_OWNER', owner2: 'ADD_OWNER', mailParts: ['MAIL_ADDR', 'MAIL_CITY', 'MAIL_STATE', 'MAIL_ZIP'], situs: 'PARCEL_ADDR', acres: 'ACRES', landUse: 'PROP_CLASS', county: 'COUNTY_NAME' },
    county: null,
    state: 'NY',
    extent: [-79.762, 40.4959, -71.8009, 45.0159],
    kind: 'statewide',
    pageSize: 1000,
    ownerCounties: {
      only: [
        'Albany', 'Bronx', 'Broome', 'Cayuga', 'Chautauqua', 'Cortland', 'Erie', 'Genesee', 'Greene', 'Hamilton', 'Kings', 'Lewis', 'Livingston', 'Montgomery', 'New York', 'Oneida', 'Onondaga', 'Ontario', 'Orange',
        'Oswego', 'Otsego', 'Putnam', 'Queens', 'Rensselaer', 'Richmond', 'Rockland', 'Schuyler', 'St. Lawrence', 'St Lawrence', 'Steuben', 'Suffolk', 'Sullivan', 'Tioga', 'Tompkins', 'Ulster', 'Warren', 'Wayne', 'Westchester', 'Wyoming',
      ],
    },
    recordsUrl: 'https://gis.ny.gov/parcels',
  },
  {
    id: 'va-statewide',
    label: 'Virginia Parcels (VGIN)',
    shortLabel: 'Virginia statewide',
    url: 'https://vginmaps.vdem.virginia.gov/arcgis/rest/services/VA_Base_Layers/VA_Parcels/FeatureServer/0',
    fields: { parcelId: 'PARCELID', county: 'LOCALITY' },
    county: null,
    state: 'VA',
    extent: [-83.6754, 36.5374, -75.2395, 39.464],
    kind: 'statewide',
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=52bbb5cd6d494817af989f33290db899',
  },
  {
    id: 'vt-statewide',
    label: 'Vermont Standardized Parcels with Grand List (VCGI)',
    shortLabel: 'Vermont statewide',
    url: 'https://services1.arcgis.com/BkFxaEFNwHqX3tAw/arcgis/rest/services/FS_VCGI_OPENDATA_Cadastral_VTPARCELS_poly_standardized_parcels_SP_v1/FeatureServer/0',
    fields: { parcelId: 'SPAN', owner: 'OWNER1', owner2: 'OWNER2', mailParts: ['ADDRGL1', 'CITYGL', 'STGL', 'ZIPGL'], situs: 'E911ADDR', acres: 'ACRESGL', landUse: 'CAT' },
    county: null,
    state: 'VT',
    extent: [-73.4542, 42.7226, -71.4654, 45.0184],
    kind: 'statewide',
    recordsUrl: 'https://vcgi.vermont.gov/data-and-programs/parcel-program',
  },
  {
    id: 'wv-statewide',
    label: 'WV Parcels (WV GIS Technical Center)',
    shortLabel: 'West Virginia statewide',
    url: 'https://services.wvgis.wvu.edu/arcgis/rest/services/Planning_Cadastre/WV_Parcels/MapServer/0',
    ownerTable: { url: 'https://services.wvgis.wvu.edu/arcgis/rest/services/Planning_Cadastre/WV_Parcels/MapServer/11', joinField: 'CleanParcelID' },
    fields: { parcelId: 'CleanParcelID', owner: 'FullOwnerName', owner2: 'OWNER2', mailParts: ['OwnerAddress1', 'OwnerCity', 'OwnerStateCode', 'OwnerZipCode'], situs: 'FullPhysicalAddress', acres: 'CALC_ACRE', landUse: 'LandUse', county: 'CountyName' },
    county: null,
    state: 'WV',
    extent: [-82.7024, 37.1601, -77.6588, 40.6359],
    kind: 'statewide',
    recordsUrl: 'https://www.mapwv.gov/parcel/',
  },

  // ---------- Central (verified 2026-10-09) ----------
  {
    id: 'ar-statewide',
    label: 'Arkansas GIS Office Parcels (CAMP)',
    shortLabel: 'Arkansas statewide',
    url: 'https://gis.arkansas.gov/arcgis/rest/services/FEATURESERVICES/Planning_Cadastre/FeatureServer/6',
    fields: { parcelId: 'parcelid', owner: 'ownername', situs: 'adrlabel', acres: 'taxarea', county: 'county' },
    county: null,
    state: 'AR',
    extent: [-94.618, 33.004, -89.647, 36.5],
    kind: 'statewide',
    pageSize: 200,
    recordsUrl: 'https://geodata.gis.arkansas.gov/',
  },
  {
    id: 'ia-statewide',
    label: 'Iowa Statewide Parcels, 2017',
    shortLabel: 'Iowa statewide (2017)',
    url: 'https://services3.arcgis.com/kd9gaiUExYqUbnoq/arcgis/rest/services/Iowa_Parcels_2017/FeatureServer/0',
    fields: { parcelId: 'STATEPARID', owner: 'DEEDHOLDER', landUse: 'PARCELCLAS', county: 'COUNTYNAME' },
    county: null,
    state: 'IA',
    extent: [-96.64, 40.376, -90.143, 43.501],
    kind: 'statewide',
    ownerAsOf: 2017,
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=d653c8836f344d17af8ee45d2176760f',
  },
  {
    id: 'in-statewide',
    label: 'Indiana Parcel Boundaries (IndianaMap)',
    shortLabel: 'Indiana statewide',
    url: 'https://gisdata.in.gov/server/rest/services/Hosted/Parcel_Boundaries_of_Indiana_Current/FeatureServer/0',
    fields: { parcelId: 'state_parcel_id', situs: 'prop_add', landUse: 'dlgf_prop_class_code', county: 'tax_county' },
    county: null,
    state: 'IN',
    extent: [-88.097, 37.772, -84.786, 41.761],
    kind: 'statewide',
    recordsUrl: 'https://www.indianamap.org/',
  },
  {
    id: 'mn-statewide',
    label: 'Minnesota Parcels, Opt-In Counties (MnGeo)',
    shortLabel: 'Minnesota statewide',
    url: 'https://enterprise.gisdata.mn.gov/aghost/rest/services/us_mn_state_mngeo/plan_parcels_open/FeatureServer/1',
    fields: {
      parcelId: 'state_pin',
      owner: 'owner_name',
      owner2: 'owner_more',
      mailName: 'tax_name',
      mailLines: ['own_add_l1', 'own_add_l2', 'own_add_l3', 'own_add_l4'],
      situsParts: ['anumber', 'st_pre_dir', 'st_name', 'st_pos_typ', 'postcomm'],
      acres: 'acres_poly',
      landUse: 'useclass1',
      county: 'co_name',
    },
    county: null,
    state: 'MN',
    extent: [-97.239, 43.499, -89.492, 49.384],
    kind: 'statewide',
    // Opted-in counties that also publish names; everywhere else, look for the county's own layer
    ownerCounties: {
      except: [
        'Beltrami', 'Blue Earth', 'Brown', 'Cottonwood', 'Dodge', 'Faribault', 'Freeborn', 'Goodhue', 'Hubbard', 'Kanabec', 'Kandiyohi', 'Kittson', 'Le Sueur', 'Lincoln',
        'Mahnomen', 'Martin', 'Meeker', 'Nicollet', 'Nobles', 'Pine', 'Redwood', 'Rock', 'Roseau', 'Sibley', 'Swift', 'Todd', 'Wadena', 'Watonwan',
        'Benton', 'Big Stone', 'Carver', 'Clay', 'Clearwater', 'Fillmore', 'Grant', 'Houston', 'Itasca', 'Lake of the Woods', 'Marshall', 'McLeod', 'Mille Lacs', 'Norman',
        'Pennington', 'Pope', 'Red Lake', 'Renville', 'Rice', 'Scott', 'Stearns', 'Traverse', 'Waseca', 'Wilkin', 'Yellow Medicine',
      ],
    },
    recordsUrl: 'https://gis.data.mn.gov/datasets/69148d3959194a05a23964cc60f6517b',
  },
  {
    id: 'ms-statewide',
    label: 'Mississippi Statewide Parcels, 2022',
    shortLabel: 'Mississippi statewide (2022)',
    url: 'https://gis.waggonereng.com/server/rest/services/Hosted/Mississippi_Parcels_Staewide/FeatureServer/3',
    fields: { parcelId: 'parno', owner: 'ownname', mailParts: ['mailadd1', 'mcity1', 'mstate1', 'mzip1'], situs: 'siteadd', acres: 'taxacres', county: 'cntyname' },
    county: null,
    state: 'MS',
    extent: [-91.735, 30.142, -88.096, 35.006],
    kind: 'statewide',
    ownerAsOf: 2022,
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=399921dbc1e646b49ab7b7b7cd26c80e',
  },
  {
    id: 'ne-statewide',
    label: 'Nebraska Statewide Parcels (NebraskaMAP)',
    shortLabel: 'Nebraska statewide',
    url: 'https://gis.ne.gov/Enterprise/rest/services/StatewideParcelsExternal/FeatureServer/0',
    fields: { parcelId: 'State_PID', situs: 'Situs_Address', acres: 'GIS_Acres', landUse: 'Classification_Code' },
    county: null,
    state: 'NE',
    extent: [-104.181, 39.904, -95.092, 43.07],
    kind: 'statewide',
    recordsUrl: 'https://www.nebraskamap.gov/',
  },
  {
    id: 'nd-statewide',
    label: 'North Dakota Parcels and Tax Roll (ND GIS Hub)',
    shortLabel: 'North Dakota statewide',
    url: 'https://services1.arcgis.com/GOcSXpzwBHyk2nog/arcgis/rest/services/NDGISHUB_Parcels/FeatureServer/0',
    ownerTable: { url: 'https://services1.arcgis.com/GOcSXpzwBHyk2nog/arcgis/rest/services/NDGISHUB_Parcels/FeatureServer/1', joinField: 'UniqueGISID' },
    fields: { parcelId: 'UniqueGISID', owner: 'OwnerName', owner2: 'Owner2Name', mailParts: ['OwnerMailingAddress', 'OwnerCity', 'OwnerState', 'OwnerZip'], situs: 'PropertyAddress', acres: 'CalculatedAcres', landUse: 'PrimaryParcelUse', county: 'CountyName' },
    county: null,
    state: 'ND',
    extent: [-104.049, 45.935, -96.555, 49.001],
    kind: 'statewide',
    recordsUrl: 'https://gishubdata-ndgov.hub.arcgis.com/',
  },
  {
    id: 'tn-statewide',
    label: 'Tennessee Property Boundaries (TN Comptroller)',
    shortLabel: 'Tennessee statewide',
    url: 'https://services1.arcgis.com/YuVBSS7Y1of2Qud1/arcgis/rest/services/Tennessee_Property_Boundaries_Public_Use/FeatureServer/0',
    fields: { parcelId: 'PARCELID', owner: 'OWNER', owner2: 'OWNER2', situs: 'ADDRESS', acres: 'DEEDAC', county: 'COUNTY_NAME', link: 'LINK_TPAD' },
    county: null,
    state: 'TN',
    extent: [-90.305, 34.983, -81.647, 36.678],
    kind: 'statewide',
    ownerCounties: { except: ['Chester', 'Davidson', 'Hamilton', 'Hickman', 'Knox', 'Montgomery', 'Rutherford', 'Shelby', 'Williamson'] },
    recordsUrl: 'https://tnmap.tn.gov/assessment/',
  },
  {
    id: 'wi-statewide',
    label: 'Wisconsin Statewide Parcels V12',
    shortLabel: 'Wisconsin statewide',
    url: 'https://services3.arcgis.com/n6uYoouQZW75n5WI/arcgis/rest/services/Wisconsin_Statewide_Parcels_DB/FeatureServer/0',
    fields: { parcelId: 'STATEID', owner: 'OWNERNME1', owner2: 'OWNERNME2', mailAddress: 'PSTLADRESS', situs: 'SITEADRESS', acres: 'GISACRES', landUse: 'PROPCLASS', county: 'CONAME' },
    county: null,
    state: 'WI',
    extent: [-92.889, 42.492, -86.764, 47.081],
    kind: 'statewide',
    recordsUrl: 'https://www.sco.wisc.edu/parcels/data/',
  },

  // ---------- West (verified 2026-10-09) ----------
  {
    id: 'ak-statewide',
    label: 'Alaska Statewide Parcels (borough and city compilation)',
    shortLabel: 'Alaska statewide',
    url: 'https://services8.arcgis.com/jzbhhVHDe3lCCWFT/arcgis/rest/services/AK_Statewide_Parcels/FeatureServer/0',
    where: "Duplicate='No'",
    fields: { parcelId: 'AgencyParcelID', owner: 'OwnerName', mailParts: ['OwnerAddress', 'OwnerCity', 'OwnerState', 'OwnerZip'], situs: 'SitusLine1' },
    county: null,
    state: 'AK',
    extent: [-166.841, 53.805, -129.995, 71.389],
    kind: 'statewide',
    ownerCounties: { only: ['Anchorage', 'Matanuska-Susitna', 'Kenai Peninsula', 'Fairbanks North Star', 'Kodiak Island', 'Ketchikan Gateway', 'North Slope', 'Denali', 'Bristol Bay', 'Haines', 'Sitka', 'Petersburg', 'Wrangell', 'Yakutat', 'Skagway', 'Nome'] },
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=6327fed1a2e04e04a1d5354fc5d9b85d',
  },
  {
    id: 'co-statewide',
    label: 'Colorado Public Parcels (OIT)',
    shortLabel: 'Colorado statewide',
    url: 'https://gis.colorado.gov/public/rest/services/Address_and_Parcel/Colorado_Public_Parcels/FeatureServer/0',
    fields: { parcelId: 'parcel_id', owner: 'owner', owner2: 'owner2', mailParts: ['ownerAdd', 'ownAddCty', 'ownAddStt', 'ownAddZip'], situs: 'situsAdd', acres: 'landAcres', landUse: 'landUseDsc', county: 'countyName' },
    county: null,
    state: 'CO',
    extent: [-109.06, 36.992, -102.047, 41.003],
    kind: 'statewide',
    ownerCounties: {
      except: ['Alamosa', 'Baca', 'Bent', 'Chaffee', 'Cheyenne', 'Conejos', 'Costilla', 'Crowley', 'Delta', 'Fremont', 'Jackson', 'Kiowa', 'Kit Carson', 'Las Animas', 'Lincoln', 'Mineral', 'Montrose', 'Otero', 'Phillips', 'Prowers', 'El Paso', 'Summit', 'Washington'],
    },
    recordsUrl: 'https://experience.arcgis.com/experience/f85c4563dab548e0bbd400df1a411e76',
  },
  {
    id: 'hi-statewide',
    label: 'Hawaii Statewide Parcels (TMK)',
    shortLabel: 'Hawaii statewide',
    url: 'https://geodata.hawaii.gov/arcgis/rest/services/ParcelsZoning/MapServer/25',
    fields: { parcelId: 'tmk_txt', acres: 'gisacres', county: 'county', link: 'qpub_link' },
    county: null,
    state: 'HI',
    extent: [-160.55, 18.893, -154.732, 22.236],
    kind: 'statewide',
    pageSize: 1000,
    recordsUrl: 'https://www.arcgis.com/home/item.html?id=579b8dcb7a8e44c1af201e1b3cdf655f',
  },
  {
    id: 'id-statewide',
    label: 'Public Idaho Parcels (Idaho ITS)',
    shortLabel: 'Idaho statewide',
    url: 'https://services1.arcgis.com/CNPdEkvnGl65jCX8/arcgis/rest/services/Public_Idaho_Parcels_/FeatureServer/7',
    fields: { parcelId: 'PARCEL_ID', owner: 'OWNER1', owner2: 'OWNER2', mailParts: ['MAIL_ADD1', 'MAIL_CITY', 'MAIL_STATE', 'MAIL_ZIP'], situs: 'SITE_ADD', acres: 'ASR_ACRES', landUse: 'ASR_CATS', county: 'County' },
    county: null,
    state: 'ID',
    extent: [-117.372, 41.96, -110.805, 46.661],
    kind: 'statewide',
    ownerCounties: { only: ['Bear Lake', 'Boise', 'Camas', 'Gooding', 'Jerome', 'Minidoka', 'Nez Perce', 'Oneida', 'Teton', 'Valley', 'Washington'] },
    recordsUrl: 'https://experience.arcgis.com/experience/cc1d9d013e584c89b448344723504b29',
  },
  {
    id: 'mt-statewide',
    label: 'Montana Cadastral (Montana State Library)',
    shortLabel: 'Montana statewide',
    url: 'https://services.arcgis.com/qnjIrwR8z5Izc0ij/arcgis/rest/services/Montana_Cadastral_Framework/FeatureServer/1',
    fields: { parcelId: 'PARCELID', owner: 'OwnerName', mailName: 'CareOfTaxpayer', mailParts: ['OwnerAddress1', 'OwnerCity', 'OwnerState', 'OwnerZipCode'], situs: 'AddressLine1', acres: 'TotalAcres', landUse: 'PropType', county: 'CountyName' },
    county: null,
    state: 'MT',
    extent: [-116.179, 44.238, -103.611, 49.181],
    kind: 'statewide',
    recordsUrl: 'https://gis.mt.gov/',
  },
  {
    id: 'nv-statewide',
    label: 'Nevada Statewide Parcels, 2018 (NDOT)',
    shortLabel: 'Nevada statewide (2018)',
    url: 'https://gis.dot.nv.gov/agsphs/rest/services/Reference/Statewide_Parcels/MapServer/0',
    fields: { parcelId: 'APN', owner: 'OwnerName', situs: 'SiteAddress', acres: 'Acres', county: 'County' },
    county: null,
    state: 'NV',
    extent: [-120.132, 34.99, -113.791, 42.035],
    kind: 'statewide',
    ownerAsOf: 2018,
    recordsUrl: 'https://gis.dot.nv.gov/agsphs/rest/services/Reference/Statewide_Parcels/MapServer',
  },
  {
    id: 'ut-statewide',
    label: 'Utah Statewide Parcels (UGRC)',
    shortLabel: 'Utah statewide',
    url: 'https://services1.arcgis.com/99lidPhWCzftIe9K/arcgis/rest/services/UtahStatewideParcels/FeatureServer/0',
    fields: { parcelId: 'PARCEL_ID', situs: 'PARCEL_ADD', county: 'County', link: 'CoParcel_URL' },
    county: null,
    state: 'UT',
    extent: [-114.053, 36.998, -109.042, 42.002],
    kind: 'statewide',
    recordsUrl: 'https://gis.utah.gov/products/sgid/cadastre/parcels/',
  },
  {
    id: 'wa-statewide',
    label: 'Washington State Current Parcels',
    shortLabel: 'Washington statewide',
    url: 'https://services.arcgis.com/jsIt88o09Q0r1j8h/arcgis/rest/services/Current_Parcels/FeatureServer/0',
    fields: { parcelId: 'PARCEL_ID_NR', situs: 'SITUS_ADDRESS', landUse: 'LANDUSE_CD', link: 'DATA_LINK' },
    county: null,
    state: 'WA',
    extent: [-124.927, 45.486, -116.711, 49.049],
    kind: 'statewide',
    recordsUrl: 'https://geo.wa.gov/datasets/wa-geoservices::current-parcels',
  },
  {
    id: 'wy-statewide',
    label: 'Wyoming Parcels 2026 (Dept of Revenue)',
    shortLabel: 'Wyoming statewide',
    url: 'https://services3.arcgis.com/r0iJ85SKZ4zAzz3P/arcgis/rest/services/Wyoming_Parcels_for_2026/FeatureServer/0',
    fields: { parcelId: 'parcelnb', owner: 'ownername1', owner2: 'ownername2', mailParts: ['mailaddres', 'mailcity', 'mailstate', 'mailzipcod'], situs: 'locationad', acres: 'landgrossa', county: 'jurisdicti' },
    county: null,
    state: 'WY',
    extent: [-111.056, 40.995, -104.052, 45.006],
    kind: 'statewide',
    recordsUrl: 'https://wyo-prop-div.maps.arcgis.com/apps/webappviewer/index.html?id=4bb9a66f7287402b8f650aa9f21d3fa5',
  },
]

export const COUNTY_REGISTRY: ParcelSource[] = [
  {
    id: 'oh-summit',
    label: 'Summit County Fiscal Office',
    shortLabel: 'Summit County',
    url: 'https://services3.arcgis.com/3Ukh5HzAdI6WZ3KP/arcgis/rest/services/TaxParcels_public/FeatureServer/0',
    fields: { parcelId: 'PARCELID', owner: 'OWNERNME1', owner2: 'OWNERNME2', mailParts: ['PSTLADDRESS', 'PSTLCITY', 'PSTLSTATE', 'PSTLZIP5'], situs: 'SITEADDRESS', acres: 'STATEDAREA', landUse: 'USEDSCRP' },
    county: 'Summit',
    state: 'OH',
    extent: [-81.7, 40.98, -81.38, 41.36],
    kind: 'county',
    recordsUrl: 'https://fiscaloffice.summitoh.net/',
  },
  {
    id: 'oh-stark',
    label: 'Stark County Auditor',
    shortLabel: 'Stark County',
    url: 'https://scgisa.starkcountyohio.gov/arcgis/rest/services/Auditor/StarkCountyParcels/FeatureServer/0',
    fields: { parcelId: 'PIN', owner: 'OWNER', mailName: 'MAILING_NAME', mailAddress: 'MAILING_ADDRESS', situs: 'SITE_ADDRESS', acres: 'ACRES', landUse: 'LAND_USE_DESCRIPTION' },
    county: 'Stark',
    state: 'OH',
    extent: [-81.66, 40.63, -81.07, 41.0],
    kind: 'county',
    recordsUrl: 'https://www.starkcountyohio.gov/auditor',
  },
  {
    id: 'oh-geauga',
    label: 'Geauga County Auditor',
    shortLabel: 'Geauga County',
    url: 'https://gcgis.geauga.oh.gov/parcel/rest/services/AzureParcels/Parcels/FeatureServer/0',
    fields: { parcelId: 'PARCEL_ID', owner: 'Oname1', owner2: 'Oname2', mailName: 'MailName1', mailParts: ['MailStreet', 'MailCitySt', 'MailZip'], situs: 'LocDesc', acres: 'ACRES', landUse: 'PropClass' },
    county: 'Geauga',
    state: 'OH',
    extent: [-81.4, 41.34, -80.99, 41.73],
    kind: 'county',
    recordsUrl: 'https://auditor.geauga.oh.gov/',
  },
  {
    id: 'de-kent',
    label: 'Kent County Parcels',
    shortLabel: 'Kent County',
    url: 'https://gis.kentcountyde.gov/server/rest/services/Parcels/Parcels/FeatureServer/0',
    fields: { owner: 'OWNERNAME', owner2: 'SECONDARYOWNER', mailParts: ['MAILINGADDRESS', 'OWNERCITY', 'OWNERSTATE', 'OWNERZIP'], acres: 'DEEDACREAGE', landUse: 'PropertyUse' },
    county: 'Kent',
    state: 'DE',
    extent: [-75.77, 38.8, -75.38, 39.4],
    kind: 'county',
    recordsUrl: 'https://www.kentcountyde.gov/',
  },
  {
    id: 'de-new-castle',
    label: 'New Castle County Parcels',
    shortLabel: 'New Castle County',
    url: 'https://gis.nccde.org/agsserver/rest/services/BaseMaps/Base_Layers/MapServer/0',
    fields: { owner: 'CNTCTLAST', mailParts: ['OWNADDR', 'OWNCITY', 'OWNSTATE', 'OWNZIP'] },
    county: 'New Castle',
    state: 'DE',
    extent: [-75.79, 39.35, -75.45, 39.84],
    kind: 'county',
    pageSize: 1000,
    allFields: true,
    recordsUrl: 'https://www.nccde.org/',
  },
  {
    // Found 2026-10-09: the county's own service, owner names and split mailing address, CORS echoes origin
    id: 'oh-portage',
    label: 'Portage County Tax Parcels',
    shortLabel: 'Portage County',
    url: 'https://services.portageco.com/arcgis/rest/services/TaxParcel_GE/FeatureServer/0',
    fields: {
      parcelId: 'PARCELID',
      owner: 'DeededOwner',
      mailParts: ['OwnStreetNumber', 'OwnStreetDirection', 'OwnStreetName', 'OwnStreetSuffix', 'OwnCity', 'OwnState', 'OwnZipcode'],
      situsParts: ['mlocStrNo', 'mlocStrDir', 'mlocStrName', 'mlocStrSuffix', 'mlocCity'],
      acres: 'CALC_AC',
      landUse: 'mClassificationId',
      link: 'CAMA',
    },
    county: 'Portage',
    state: 'OH',
    extent: [-81.42, 40.99, -81.0, 41.36],
    kind: 'county',
    recordsUrl: 'https://www.co.portage.oh.us/auditor',
  },
]
